# Generated by Django 5.0.6 on 2024-06-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mypicture',
            new_name='picture',
        ),
    ]
